## Elasticsearch configuration
Elasticsearch nodes:
  cluster.initial_master_nodes:
          - <master_node_1>
          # - <master_node_2>
          # - <master_node_3>

  discovery.seed_hosts:
          - <elasticsearch_ip_node1>
          # - <elasticsearch_ip_node2>
          # - <elasticsearch_ip_node3>

# Wazuh-master configuration
Wazuh servers IPs:

  name:
    - <node_name>
  ip:
    - <wazuh_master_server_IP_1>
  # name:
  #   - <node_name>
  # ip:
  #   - <wazuh_master_server_IP_2>

# Kibana configuration
Kibana IP:
  name:
    - node-name
  ip:
    - <kibana_ip>