## Elasticsearch configuration
Elasticsearch nodes:
  cluster.initial_master_nodes:
          - <master_node_1>
          # - <master_node_2>
          # - <master_node_3>

  discovery.seed_hosts:
          - <elasticsearch_ip_node1>
          # - <elasticsearch_ip_node2>
          # - <elasticsearch_ip_node3>

# Wazuh-master configuration
Wazuh servers IPs:
  - <wazuh_master_server_IP_1>
  # - <wazuh_master_server_IP_2>

# Kibana configuration
Kibana IP:
  - <kibana_ip>