## Multi-node configuration

## Elasticsearch configuration

cluster.name: <elastic_cluster>

cluster.initial_master_nodes:
        - <master_node_1>
        - <master_node_2>
        - <master_node_3>

discovery.seed_hosts:
        - <elasticsearch_ip_node1>
        - <elasticsearch_ip_node2>
        - <elasticsearch_ip_node3>

# Wazuh server nodes
wazuh-servers:
  - name: <node-name-1>
    ip:
      - node-IP   
  - name: <node-name-2>
    ip:
      - node-IP  


# Kibana-instance
- <kibana_ip>

# Wazuh-master-configuration
- <wazuh_master_server_IP>